In [1]:
import numpy as np
import pandas as pd

In [2]:
table = pd.read_excel('test.xlsx')

In [3]:
list_names = ['Возраст', 'Диагноз']

In [5]:
def descriptive_statistics(table, columns_names = None):

    if columns_names is None:
        descriptive_statistics_table = table.describe()
        columns_names = descriptive_statistics_table.columns.values.tolist()

        count_NAN = table[columns_names].isnull().sum()
        SEM = table[columns_names].describe().loc['std'] / np.sqrt(len(table) - count_NAN)

        new_line_sem = SEM.T.to_frame().T
        new_line_sem.index = ['SEM']

        #descriptive_statistics_frame = descriptive_statistics.to_frame()
        descriptive_statistics = pd.concat([descriptive_statistics_table,new_line_sem])


    else:
        descriptive_statistics = table[columns_names].describe()
        count_NAN = table[columns_names].isnull().sum()
        SEM = table[columns_names].describe().loc['std'] / np.sqrt(len(table) - count_NAN)

        new_line_sem = SEM.T.to_frame().T
        new_line_sem.index = ['SEM']

        descriptive_statistics = pd.concat([descriptive_statistics,new_line_sem])


    return  descriptive_statistics

In [7]:
descriptive_statistics(table)

           Номер    Возраст    Болезнь    Диагноз
count  29.000000  29.000000  29.000000  29.000000
mean   15.000000  35.655172   0.482759   2.793103
std     8.514693  26.566999   0.508548   1.473075
min     1.000000   1.000000   0.000000   1.000000
25%     8.000000   7.000000   0.000000   1.000000
50%    15.000000  36.000000   0.000000   3.000000
75%    22.000000  57.000000   1.000000   4.000000
max    29.000000  90.000000   1.000000   5.000000
SEM     1.581139   4.933368   0.094435   0.273543

In [111]:
count_NAN = table[list_names].isnull().sum()

SEM = table[list_names].describe().loc['std'] / np.sqrt(len(table) - count_NAN)
#

In [113]:
c = SEM.T.to_frame().T

c.index = ['SEM']

c

      Возраст   Диагноз
SEM  4.933368  0.273543

In [44]:
count_NAN

Возраст    0
Диагноз    0
dtype: int64